# El entorno I3
exec --no-startup-id dex --autostart --environment i3
exec_always ~/.config/polybar/launch.sh
exec_always setxkbmap latam
exec_always --no-startup-id ~/.screenlayout/monitor.sh
exec_always --no-startup-id lxpolkit &
#exec_always --no-startup-id wireplumber
exec_always --no-startup-id pipewire
#exec_always --no-startup-id picom
exec_always --no-startup-id picom -f
exec_always --no-startup-id ~/.scripts/display.sh
exec --no-startup-id sh -c 'feh --bg-fill "$(cat ~/.config/matugen/wallpaper.txt)"'
