# Configuración de Pantalla Generada Dinámicamente
# NO EDITAR ESTE ARCHIVO DIRECTAMENTE
exec_always --no-startup-id xrandr --output HDMI-1 --mode 1920x1080 --transform none --rotate normal --brightness 1.0
