# --- Main Colors ---
background            {{ colors.surface_container_low.default.hex }}
foreground            {{ colors.on_surface.default.hex | set_lightness: 95 }}
cursor                {{ colors.primary.default.hex | set_lightness: 75 }}
cursor_text_color     {{ colors.surface_container_low.default.hex }}

selection_background  {{ colors.primary_container.default.hex | set_lightness: 18 }}
selection_foreground  {{ colors.on_primary_container.default.hex | set_lightness: 85 }}

url_color             {{ colors.tertiary.default.hex | set_lightness: 70 }}

# --- ANSI Colors (Pasteles Desaturados en Acentos + Blancos Nítidos) ---
# normal (Luminosidad 55% para tono pastel lavado)
color0                {{ colors.surface.default.hex }}
color1                {{ colors.error.default.hex | set_lightness: 55 }}
color2                {{ colors.tertiary.default.hex | set_lightness: 55 }}
color3                {{ colors.secondary.default.hex | set_lightness: 55 }}
color4                {{ colors.primary.default.hex | set_lightness: 55 }}
color5                {{ colors.inverse_primary.default.hex | set_lightness: 55 }}
color6                {{ colors.secondary.default.hex | set_lightness: 60 }}
color7                {{ colors.on_surface_variant.default.hex | set_lightness: 85 }}

# bright (Luminosidad 72/75% para acentos, y 98% para blanco brillante)
color8                {{ colors.surface_variant.default.hex }}
color9                {{ colors.error.default.hex | set_lightness: 72 }}
color10               {{ colors.tertiary.default.hex | set_lightness: 72 }}
color11               {{ colors.secondary.default.hex | set_lightness: 72 }}
color12               {{ colors.primary.default.hex | set_lightness: 72 }}
color13               {{ colors.inverse_primary.default.hex | set_lightness: 72 }}
color14               {{ colors.secondary.default.hex | set_lightness: 75 }}
color15               {{ colors.on_surface.default.hex | set_lightness: 98 }}

# --- UI Elements ---
active_tab_foreground   {{ colors.on_primary.default.hex }}
active_tab_background   {{ colors.primary.default.hex }}
inactive_tab_foreground {{ colors.on_primary_container.default.hex }}
inactive_tab_background {{ colors.primary_container.default.hex }}

active_border_color     {{ colors.primary.default.hex }}
inactive_border_color   {{ colors.outline.default.hex }}
