style:Estilo:square,round
position:Posición:bottom,top
transparency:Transparencia:true,false
height:Altura:15pt,13pt,18pt,20pt,custom
mode:Mode:solid,underline
rofi_style:Rofi Style:solid,underline
solid_line:Solid Line:true,false
