background #1a1110
foreground #f1dedc
color0  #1a1110
color1  #ffb4ab
color2  #ffb4ab
color3  #e0c38c
color4  #e7bdb8
color5  #5d3f3c
color6  #584419
color7  #f1dedc
color8  #a08c8a
color9  #93000a
color10 #73332e
color11 #e0c38c
color12 #e7bdb8
color13 #ffdad6
color14 #fddfa6
color15 #f1dedc
