background #1c0f19
foreground #f4dcea
color0  #1c0f19
color1  #ffb4ab
color2  #ffaced
color3  #cecc4f
color4  #ffaced
color5  #83127a
color6  #b2b036
color7  #f4dcea
color8  #a4899b
color9  #93000a
color10 #fa2ee9
color11 #cecc4f
color12 #ffaced
color13 #ffd9f3
color14 #222200
color15 #f4dcea
