# Fuente para los titulos de ventanas
font pango:google sans 9

set_from_resource $fg i3wm.color7 #f0f0f0
set_from_resource $bg i3wm.color8 #f0f0f0
set_from_resource $bga i3wm.color4  #f0f0f0
# class                 border  backgr. text indicator child_border
client.focused          $bga     $bga     $fg  $bga       $bga
client.focused_inactive $bg     $bg     $fg  $bg       $bg
client.unfocused        $bg     $bg     $fg  $bg       $bg
client.urgent           $bg     $bg     $fg  $bg       $bg
client.placeholder      $bg     $bg     $fg  $bg       $bg

client.background       $bg


#margen
#smart_gaps on
smart_borders on
set $inner_gaps 5
set $outer_gaps 5

gaps inner $inner_gaps
gaps outer $outer_gaps

hide_edge_borders vertical
