exec_always ~/.config/polybar/launch.sh
exec_always setxkbmap latam
exec_always --no-startup-id picom -f
exec_always --no-startup-id $dots_cmd $current_env wp_select.sh -C "$(cat ~/.config/i3/wall)"
exec --no-startup-id ~/.local/bin/recolor_folders --restore
