[ColorScheme]
active_colors=#f4dcea, #1c0f19, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f4dcea, #ffffff, #f4dcea, #1c0f19, #1c0f19, #000000, #fa2ee9, #000000, #ffaced, #ffaced, #1c0f19, #000000, #1c0f19, #f4dcea, #ffaced
disabled_colors=#f4dcea, #1c0f19, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f4dcea, #ffffff, #f4dcea, #1c0f19, #1c0f19, #000000, #fa2ee9, #000000, #ffaced, #ffaced, #1c0f19, #000000, #1c0f19, #f4dcea, #ffaced
inactive_colors=#f4dcea, #1c0f19, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f4dcea, #ffffff, #f4dcea, #1c0f19, #1c0f19, #000000, #fa2ee9, #000000, #ffaced, #ffaced, #1c0f19, #000000, #1c0f19, #f4dcea, #ffaced

