[ColorScheme]
active_colors=#fadcd8, #1e0f0e, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #fadcd8, #ffffff, #fadcd8, #1e0f0e, #1e0f0e, #000000, #da2f2c, #ffffff, #ffb4ab, #ffb4ab, #1e0f0e, #000000, #1e0f0e, #fadcd8, #ffb4ab
disabled_colors=#fadcd8, #1e0f0e, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #fadcd8, #ffffff, #fadcd8, #1e0f0e, #1e0f0e, #000000, #da2f2c, #ffffff, #ffb4ab, #ffb4ab, #1e0f0e, #000000, #1e0f0e, #fadcd8, #ffb4ab
inactive_colors=#fadcd8, #1e0f0e, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #fadcd8, #ffffff, #fadcd8, #1e0f0e, #1e0f0e, #000000, #da2f2c, #ffffff, #ffb4ab, #ffb4ab, #1e0f0e, #000000, #1e0f0e, #fadcd8, #ffb4ab

